### ISSUE TITLE
a question with the demo run

### ISSUE THREAD

**Issue by WeiViming** [brianhie/secure-dti#3]
Hello,
I have a question with the demo.
When I try to run 
`./bin/ShareData 3 ../par/demo.par.3.txt ../../demo_data/batch_pw/ &` on same machine with different terminals,
it return `ShareData: mpc.cpp:2221: void MPCEnv::Write(Mat<NTL::ZZ_p> &, std::fstream &):  Assertion ofs.is_open()' failed.`
Do you have any idea to solve this problem? Much thanks! :)

**Comment by brianhie** [comment]
@WeiViming I'm not sure, I haven't seen that problem myself and it's hard to debug remotely. Perhaps make sure you have read/write permissions to the file that the stream is referencing, or make sure that the file/directory exists?

**Comment by WeiViming** [comment]
@brianhie Thanks！
